### ISSUE TITLE
Error on production build

### ISSUE THREAD

**Issue by mjcabalar** [finmavis/razzle-plugin-purgecss#10]
Hi, I got this error on a production build. I don't get this error if I remove the purgecss plugin.  

\...\node_modules\razzle\scripts\build.js:127
        clientStats.toJson({}, true)
                    ^
TypeError: Cannot read property 'toJson' of undefined
    at compile (\...\node_modules\razzle\scripts\build.js:127:21)
    at compiler.run (\...\node_modules\razzle\scripts\build.js:214:5)
    at finalCallback (\...\node_modules\webpack\lib\Compiler.js:257:39)
    at onCompiled (\...\node_modules\webpack\lib\Compiler.js:265:20)

razzle.config.js

module.exports = {
  plugins: [
      'serviceworker',
      {
        name: 'purgecss',
        options: {
          path: path.resolve(__dirname, './src/**/*'),  
        }
      }
  ]
}

**Comment by finmavis** [comment]
Hi, thank you for reporting issue, I'll look into it

**Comment by mjcabalar** [comment]
Thank you! By the way, I'm using razzle 3.1.3 version, what seems to be the problem? Does it conflict with the new config?

**Comment by finmavis** [comment]
Hi, I already tried to reproduce it, it seems like I got no error.

```
Razzle: 3.1.3
PurgeCSS Plugin: 1.0.1
Service Worker Plugin: 1.0.3
Offline Plugin: 5.0.7
```

**Comment by mjcabalar** [comment]
I also tried to install a new razzle app and it's working fine.
But still can't get it to work with my existing project.

Here's my razzle.config.js

```
'use strict'
const path = require('path');

module.exports = {
  plugins: [
      'serviceworker',
      {
        name: 'purgecss',
        options: {
          path: path.resolve(__dirname, 'src/**/*')
        }
      }
  ],
  modify(config, { target, dev }) {
    const appConfig = Object.assign({}, config);
    
    if (target === 'node' && !dev) {
      appConfig.devtool = false;
      appConfig.entry = path.resolve(__dirname, './src/server');
      appConfig.output.filename = 'server.bundle.js';
      appConfig.output.path = path.resolve(__dirname, './bundle/build');
      appConfig.output.libraryTarget = 'commonjs2';
    }

    return appConfig;
  },
}
```

The error I got on production build

```
Creating an optimized production build...
Compiling client...
D:\ss\node_modules\razzle\scripts\build.js:127
        clientStats.toJson({}, true)
                    ^

TypeError: Cannot read property 'toJson' of undefined
    at compile (D:\ss\node_modules\razzle\scripts\build.js:127:21)
    at compiler.run (D:\ss\node_modules\razzle\scripts\build.js:214:5)
    at finalCallback (D:\ss\node_modules\webpack\lib\Compiler.js:257:39)
    at onCompiled (D:\ss\node_modules\webpack\lib\Compiler.js:265:20)
    at compilation.seal.err (D:\ss\node_modules\webpack\lib\Compiler.js:676:23)
    at hooks.additionalAssets.callAsync.err (D:\ss\node_modules\webpack\lib\Compilation.js:1407:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\ss\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:12:1)    at AsyncSeriesHook.lazyCompileHook (D:\ss\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (D:\ss\node_modules\webpack\lib\Compilation.js:1405:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\ss\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1) 
    at AsyncSeriesHook.lazyCompileHook (D:\ss\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (D:\ss\node_modules\webpack\lib\Compilation.js:1342:27)
    at compilation.finish.err (D:\ss\node_modules\webpack\lib\Compiler.js:675:18)
    at hooks.finishModules.callAsync.err (D:\ss\node_modules\webpack\lib\Compilation.js:1261:4)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\ss\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)    at AsyncSeriesHook.lazyCompileHook (D:\ss\node_modules\tapable\lib\Hook.js:154:20)
```

my package.json

 ```
 "dependencies": {
    "express": "^4.17.1",
    "firebase": "^6.6.2",
    "firebase-admin": "^8.12.1",
    "firebase-functions": "^3.6.2",
    "query-string": "^6.13.0",
    "razzle": "^3.1.3",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.2.0",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "offline-plugin": "^5.0.7",
    "razzle-plugin-purgecss": "^1.0.1",
    "razzle-plugin-serviceworker": "^1.0.3"
  }
```

**Comment by finmavis** [comment]
I'm afraid that I still got no error, and I just tested it on one of my projects,

I need to dig a bit more, it'll take a bit times,

**Comment by mjcabalar** [comment]
I don't know what seems to be the problem, tested it on my other projects and it's working but also noticed that on my css module it is ignoring the classname with underscore and compiles only those classname with dash. Is it bad to use classname like this `.class_name` ?

**Comment by finmavis** [comment]
To make PurgeCSS works with CSS Modules, you need to use PostCSS and the PurgeCSS PostCSS plugin. You can read more in here https://purgecss.com/css_modules.html

**Comment by mjcabalar** [comment]
That might seem the problem on my existing razzle project, I'm using CSS modules in it.
